matrix:
  include:
  - os: linux
    language: node_js
    node_js: '9'
    sudo: required
    dist: xenial
    addons:
      apt:
        packages:
        - google-chrome-stable
        - openjpeg-tools
        - rpm
        - bsdtar
        - snapd
        - xvfb
        - libxtst6
        - libxss1
        - libgtk2.0-0
        - libnss3
        - libasound2
        - libdbus-1-dev
        - libglib2.0-dev
        - libgconf-2-4
        - libdbus-1-dev:i386
        - libdbus-glib-1-dev
  - os: osx
    language: node_js
    osx_image: xcode9
    node_js: '9'
    sudo: required
    env:
    - HOMEBREW_CASK_OPTS='--appdir=/Applications'
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
before_install:
- openssl aes-256-cbc -K $encrypted_0b5df9aa1433_key -iv $encrypted_0b5df9aa1433_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- echo -e "Host aur.archlinux.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update > /dev/null
    brew cask install google-chrome
  fi
cache:
  yarn: true
  directories:
  - node_modules
  - src/node_modules
  - "$(npm config get prefix)/lib/node_modules"
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/docker"
install:
- yarn
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    export DISPLAY=':99.0'
    Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    sleep 3
    sudo snap install snapcraft --classic
  fi
script:
- yarn run lint || travis_terminate 1
- yarn run build || travis_terminate 1
# TODO re-enable for linux
-  |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    yarn run test-e2e -- --retries 2 || travis_terminate 1
  fi
after_success:
- |
  if [ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]; then
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      # Only create snap in when untagged, otherwise snaps build service will do this for us
      # if [ -z $TRAVIS_TAG ]; then
      #   sed -i "s/\"AppImage\",/\"AppImage\",\"snap\",/g" package.json
      # fi
      yarn run release:linux
    else
      yarn run release:mac
    fi
  fi
deploy:
  on:
    condition: $TRAVIS_OS_NAME == "linux"
    tags: true
  provider: script
  script: bash scripts/deploy.sh $GH_TOKEN $TRAVIS_BUILD_NUMBER $TRAVIS_TAG
  skip_cleanup: true
dd:
  secure: Br5Y8lWXttRgS9MoxmoXJ3BYcc0+lsaHy8sBeoduwtdLIped0OWUq1VWfLO2H11pMCXAFY60Rw1USbm2wGnOp8nx9L1Yo9Nq5sSzaEEujKaS3hetnuGGFsj+2tOuDQ+envWFByzuLfPpAGJNGN3A7k0GYYNUi3kzxJRy1W0d4gfDPpo38X/AVw9kCQS4gXvkk2twWI3fGRlBPnAilzCfTz69aEo850Er/TYvZfMbj9tjJa2HO8l40EXpey7s5ZbrGQJjLM+eCDekmIoDOeWlbzyFj4K3SFhUpAacPvseuF2GCbj4mPPzPlNT0md85JjhNbGQgTmuWHF9iD7ULUDSHwVyFZePW8KDuZzns9oKx5qdbM8ATh8D4b4z03LlE1vPBH3Klij7WfFp0yLZq/PaUWhVvP6Br1KZrMByMrlaEA/Dn8Xw6Sbed8ipG9NZDjPVU4fh2onrEw/He09DWfddoRbYGgkNKKOPbR2mTO5qnFtWz25LX26q/cq2Eh4Twt3imE1EqMdWZ3DbGzoakhTkJCZmGj11TCgBJ5nmV8gJ/FwGjv49zWg2kdM2EgQVpTDvD++wh3LMboBfADoA/tEDF2qZxOF0Looa/Vnph0MU6843YyfY0MAhLDZ/Vj+231De5J413QItVBMw2JPKNnoR6FAmkoO9nuv5EzBf7je3XjE=
